version: '3.4'

services:
  coreapitemplate.api:
    image: ${DOCKER_REGISTRY-}coreapitemplateapi
    build:
      context: .
      dockerfile: CoreApiTemplate.Api/Dockerfile
    expose:
      - "80"

  proxy:
    image: ${DOCKER_REGISTRY-}coreapitemplatenginx
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - coreapitemplate.api