version: '3.4'

services:
  coreapitemplate.api:
    image: ${DOCKER_REGISTRY-}coreapitemplateapi
    build:
      context: .
      dockerfile: CoreApiTemplate.Api/Dockerfile
    expose:
      - "80"
      - "443"

  proxy:
    image: ${DOCKER_REGISTRY-}nginx
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80"
      - "443"
    depends_on:
      - coreapitemplate.api